// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyvesxrociwxisipihxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5dmVzeHJvY2l3eGlzaXBpaHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjc2MzIsImV4cCI6MjA3MjkwMzYzMn0.z7Zha_sfo4CgCv3FWrMtL1d4dQJlh8mT5BTEyRhiNZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});